name: sustainity

packages:
  - "sustainity_frontend"

scripts:
  check:
    run: cd sustainity_frontend && flutter analyze

  build:
    # Dart2jsOptimization ias required by Google ananlytics
    run: cd sustainity_frontend && flutter analyze && flutter build web --web-renderer html --no-tree-shake-icons --dart-define=Dart2jsOptimization=O9

  test:
    run: cd sustainity_frontend && flutter test
  
  run:
    run: cd sustainity_frontend && flutter run
  
  check_format:
    run: melos exec -- dart format .
    descritption: Check code formating
  
  fix_format:
    run: melos exec -- dart format . --fix
    descritption: Reformat the code

  fetch_assets:
    run: ./scripts/fetch_assets.sh
