name: sustainity

packages:
  - "sustainity_frontend"

scripts:
  check:
    run: cd sustainity_frontend && flutter analyze

  build:
    run: cd sustainity_frontend && flutter analyze && flutter build web --web-renderer html --no-tree-shake-icons

  test:
    run: cd sustainity_frontend && flutter test
  
  run:
    run: cd sustainity_frontend && flutter run
  
  format_check:
    run: melos exec -- dart format .
    descritption: Check code formating
  
  format_fix:
    run: melos exec -- dart format . --fix
    descritption: Reformat the code

  fetch_assets:
    run: ./scripts/fetch_assets.sh
