name: sustainity_backend
description: sustainity.dev backend serving Sustainity REST API.
version: 1.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  arango_driver: ^3.6.1
  json_annotation: ^4.8.0
  json_serializable: ^6.5.4
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  sustainity_api:
    path: ../sustainity_api

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.0
