name: sustainity_frontend
description: sustainity.dev frontend.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  countries_utils: ^1.0.1
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.14
  json_annotation: ^4.8.0
  json_serializable: ^6.5.4
  logging: ^1.2.0
  url_launcher: ^6.1.11

  sustainity_api:
    git:
      url: https://github.com/sustainity-dev/sustainity-api-dart.git
      ref: main
      path: sustainity-api
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - images/main.png
    - images/bcorp.png
    - images/eu_ecolabel.png
    - images/tco.png
    - images/fti.png

