name: CI

on:
  pull_request:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  ci:
    name: Build and test the apps
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Configure
        run: dart pub global activate melos

      - name: Format
        run: melos run format_check
      
      - name: Generate
        run: melos run generate          

      - name: Assets
        run: melos run fetch_assets

      - name: Build
        run: melos run compile          

      - name: Test
        run: melos run test          

      - name: Backend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-backend
          path: sustainity_backend/sustainity_backend
          retention-days: 1
      
      - name: Frontend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-frontend
          path: sustainity_frontend/build/web
          retention-days: 1
  
  docker:    
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: ci

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            context: ./docker/backend 
            image: wojciechkluczka/sustainity-backend
          - name: frontend
            context: ./docker/frontend 
            image: wojciechkluczka/sustainity-frontend

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}
          tags: |
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major }}.{{ minor }}
            type=ref,event=pr
      
      - name: Settings
        run: |
          echo "github.ref_type -> ${{ github.ref_type }}"
          echo "github.ref -> ${{ github.ref }}"
          echo "tags: ${{ steps.metadata.outputs.tags }}"
          echo "labels: ${{ steps.metadata.outputs.labels }}"

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Artifacts (${{ matrix.name }})
        uses: actions/download-artifact@v2
        with:
          name: artifacts-${{ matrix.name }} 
          path: ./docker/${{ matrix.name }}/artifacts/

      - name: Image (${{ matrix.name }})
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: ${{ github.ref_type == 'tag' }}
      