name: CI

on: [push, pull_request]

jobs:

  ci:
    name: Build and test the libs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Info
        run: dart info

      - name: Configure
        run: dart pub global activate melos

      - name: Build
        run: melos run compile

      - name: Format
        run: melos run check_format

      - name: Test
        run: melos run test
